# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration
version: build{build}

skip_tags: true

image: Visual Studio 2015

platform:
  - Win64

environment:
  global:
    release_description: "
      MachinekitClient_Development and QtQuickVcp_Development modules for
      x64 (64-bit Intel/AMD) Linux systems (Portable AppImages),
      Windows 32bit and 64bit (x86 zip and x64 zip),
      x64 (64-bit Intel/AMD) MacOSX systems.
      Automated builds of the master development branch. FOR TESTING PURPOSES ONLY!
      Extract the contents of the archive to your Qt installation folder to use it.
      "

  matrix:
   - QTDIR: C:\Qt\5.9\msvc2015_64
     VSVER: 14.0
     ARCH: x64
   - QTDIR: C:\Qt\5.9\msvc2015
     VSVER: 14.0
     ARCH: x86

configuration:
  - release

install:
  - ps: $env:release_tag = &git rev-parse --short $env:APPVEYOR_REPO_COMMIT
  - '%QTDIR%\bin\qtenv2.bat'
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'
  - qmake -v

build_script:
  - CALL %APPVEYOR_BUILD_FOLDER%/build/appveyor/appveyor.bat

artifacts:
  - path: 'build.release\MachinekitClient*x86.zip'
    name: MachinekitClient-x86-archive
  - path: 'build.release\QtQuickVcp*-*-*-*-Windows-x86.zip'
    name: QtQuickVcp-x86-archive
  - path: 'build.release\MachinekitClient*x64.zip'
    name: MachinekitClient-x64-archive
  - path: 'build.release\QtQuickVcp*-*-*-*-Windows-x64.zip'
    name: QtQuickVcp-x64-archive

deploy:
- description: $(release_description)
  provider: GitHub
  auth_token:
    secure: M9qlWKrBp+EjFfJen7YozWiJ1EjVaeLo2qfDKZsSgI4/X6N8HSub1cDTX4N6z/rk
  artifact: QtQuickVcp-x64-archive
  tag: $(release_tag)
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false

- description: $(release_description)
  provider: GitHub
  auth_token:
    secure: M9qlWKrBp+EjFfJen7YozWiJ1EjVaeLo2qfDKZsSgI4/X6N8HSub1cDTX4N6z/rk
  artifact: MachinekitClient-x64-archive
  tag: $(release_tag)
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false

- provider: BinTray
  username: machinekoder
  api_key:
    secure: W+r/AcwTE6+ZntNkPg4ulGEWL9A51GF0UkCqT7OqS1OSLZZHrn9MUQdoODQulAaZ
  subject: machinekoder
  repo: QtQuickVcp
  package: QtQuickVcp-Windows-master-x64
  publish: true
  override: true
  explode: false
  artifact: QtQuickVcp-x64-archive
  version: $(appveyor_build_version)
  on:
    appveyor_repo_tag: true

- provider: BinTray
  username: machinekoder
  api_key:
    secure: W+r/AcwTE6+ZntNkPg4ulGEWL9A51GF0UkCqT7OqS1OSLZZHrn9MUQdoODQulAaZ
  subject: machinekoder
  repo: MachinekitClient
  package: MachinekitClient-Windows-x64
  publish: true
  override: true
  explode: false
  artifact: MachinekitClient-x64-archive
  version: $(appveyor_build_version)
  on:
    appveyor_repo_tag: true

- description: $(release_description)
  provider: GitHub
  auth_token:
    secure: M9qlWKrBp+EjFfJen7YozWiJ1EjVaeLo2qfDKZsSgI4/X6N8HSub1cDTX4N6z/rk
  artifact: QtQuickVcp-x86-archive
  tag: $(release_tag)
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false

- description: $(release_description)
  provider: GitHub
  auth_token:
    secure: M9qlWKrBp+EjFfJen7YozWiJ1EjVaeLo2qfDKZsSgI4/X6N8HSub1cDTX4N6z/rk
  artifact: MachinekitClient-x86-archive
  tag: $(release_tag)
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false

- provider: BinTray
  username: machinekoder
  api_key:
    secure: W+r/AcwTE6+ZntNkPg4ulGEWL9A51GF0UkCqT7OqS1OSLZZHrn9MUQdoODQulAaZ
  subject: machinekoder
  repo: QtQuickVcp
  package: QtQuickVcp-Windows-x86
  publish: true
  override: true
  explode: false
  artifact: QtQuickVcp-x86-archive
  version: $(appveyor_build_version)
  on:
    appveyor_repo_tag: true

- provider: BinTray
  username: machinekoder
  api_key:
    secure: W+r/AcwTE6+ZntNkPg4ulGEWL9A51GF0UkCqT7OqS1OSLZZHrn9MUQdoODQulAaZ
  subject: machinekoder
  repo: MachinekitClient
  package: MachinekitClient-Windows-x86
  publish: true
  override: true
  explode: false
  artifact: MachinekitClient-x86-archive
  version: $(appveyor_build_version)
  on:
    appveyor_repo_tag: true
